### ISSUE TITLE
Controllers are public (no auth required)

### ISSUE THREAD

**Issue by bzbetty** [XCentium/XBlog#1]
It appears that /api/sitecore/XBlog/Create action is not authenticated at all, i'm guessing this means given the right request someone could create a blog on your site.

**Comment by bzbetty** [comment]
Actually the import controller looks like it may be able to write files to the data folder unauthenticated too.

**Comment by zmalmquist** [comment]
Thank you for taking the time to find these issues.  The controllers now require Sitecore Admin rights to use.
